/**
 * hls-package.ts — HLS adaptive bitrate packaging
 *
 * PURPOSE:
 *   Packages a rendered variant MP4 into HLS (HTTP Live Streaming) with
 *   multiple quality renditions. The player auto-selects the best quality
 *   based on the viewer's real-time bandwidth.
 *
 * RENDITIONS:
 *   - 1080p: Stream-copy from source (instant, no re-encoding)
 *   - 720p:  Re-encode at CRF 24, max 3Mbps
 *   - 480p:  Re-encode at CRF 26, max 1.5Mbps
 *
 * FORMAT:
 *   fMP4/CMAF segments (.m4s + init.mp4) with 6-second segment duration.
 *   CMAF is the modern standard — smaller than MPEG-TS, works in all browsers
 *   via hls.js and natively in Safari.
 *
 * OUTPUT STRUCTURE:
 *   {outputDir}/
 *     1080p/playlist.m3u8, init.mp4, seg000.m4s, seg001.m4s, ...
 *     720p/playlist.m3u8, init.mp4, seg000.m4s, seg001.m4s, ...
 *     480p/playlist.m3u8, init.mp4, seg000.m4s, seg001.m4s, ...
 *     master.m3u8  (generated by generateMasterPlaylist)
 *
 * USED BY:
 *   - video-processor.ts (processHlsPackage job handler)
 */

import { runFFmpeg } from "./commands";
import * as fs from "fs/promises";
import * as path from "path";

export interface HlsRendition {
  name: string;
  width: number;
  height: number;
  bandwidth: number;
  /** If true, stream-copy from source (no re-encode). */
  copy: boolean;
  crf?: number;
  maxrate?: string;
  bufsize?: string;
}

export const HLS_RENDITIONS: HlsRendition[] = [
  {
    name: "1080p",
    width: 1920,
    height: 1080,
    bandwidth: 5_000_000,
    copy: true,
  },
  {
    name: "720p",
    width: 1280,
    height: 720,
    bandwidth: 3_000_000,
    copy: false,
    crf: 24,
    maxrate: "3M",
    bufsize: "6M",
  },
  {
    name: "480p",
    width: 854,
    height: 480,
    bandwidth: 1_500_000,
    copy: false,
    crf: 26,
    maxrate: "1.5M",
    bufsize: "3M",
  },
];

/**
 * Package a single rendition into HLS fMP4 segments.
 *
 * For the 1080p rendition, uses stream-copy (instant).
 * For 720p/480p, re-encodes with libx264 at the specified CRF.
 */
export async function packageRendition(
  inputPath: string,
  outputDir: string,
  rendition: HlsRendition
): Promise<void> {
  const renditionDir = path.join(outputDir, rendition.name);
  await fs.mkdir(renditionDir, { recursive: true });

  const playlistPath = path.join(renditionDir, "playlist.m3u8");

  const args: string[] = ["-i", inputPath];

  if (rendition.copy) {
    // Stream-copy: no re-encoding, instant
    args.push("-c:v", "copy", "-c:a", "copy");
  } else {
    // Re-encode at target resolution
    const videoFilter = [
      `scale=${rendition.width}:${rendition.height}:force_original_aspect_ratio=decrease`,
      `pad=${rendition.width}:${rendition.height}:(ow-iw)/2:(oh-ih)/2`,
      "setsar=1",
    ].join(",");

    args.push(
      "-vf",
      videoFilter,
      "-c:v",
      "libx264",
      "-preset",
      "medium",
      "-crf",
      String(rendition.crf),
      "-profile:v",
      "high",
      "-level",
      "4.0",
      "-pix_fmt",
      "yuv420p",
      "-maxrate",
      rendition.maxrate!,
      "-bufsize",
      rendition.bufsize!,
      // Keyframe alignment: 6s segments at 30fps = 180 frames
      "-g",
      "180",
      "-keyint_min",
      "180",
      "-sc_threshold",
      "0",
      "-c:a",
      "aac",
      "-b:a",
      "96k",
      "-ar",
      "44100",
      "-ac",
      "2"
    );
  }

  // HLS fMP4 output options
  args.push(
    "-f",
    "hls",
    "-hls_time",
    "6",
    "-hls_playlist_type",
    "vod",
    "-hls_segment_type",
    "fmp4",
    "-hls_fmp4_init_filename",
    "init.mp4",
    "-hls_segment_filename",
    path.join(renditionDir, "seg%03d.m4s"),
    "-y",
    playlistPath
  );

  // 1080p copy is instant; 720p/480p re-encode can take 5-15 min each
  const timeout = rendition.copy ? 300_000 : 1_200_000;
  await runFFmpeg(args, timeout);
}

/**
 * Generate the HLS master playlist (master.m3u8) referencing all renditions.
 *
 * The master playlist tells the player which quality levels are available
 * and their bandwidth requirements. The player selects the best one based
 * on current network conditions.
 */
export async function generateMasterPlaylist(
  outputDir: string,
  renditions: HlsRendition[]
): Promise<string> {
  const lines: string[] = ["#EXTM3U", "#EXT-X-VERSION:7"];

  for (const r of renditions) {
    lines.push(
      `#EXT-X-STREAM-INF:BANDWIDTH=${r.bandwidth},RESOLUTION=${r.width}x${r.height},CODECS="avc1.640028,mp4a.40.2"`
    );
    lines.push(`${r.name}/playlist.m3u8`);
  }

  const masterPath = path.join(outputDir, "master.m3u8");
  await fs.writeFile(masterPath, lines.join("\n") + "\n");
  return masterPath;
}
